config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'rooms#index'

  resources :rooms
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many_attached :images, dependent: :destroy
  validates :title, presence: true
  validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: {maximum: 10}
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  def index
    @rooms = Room.all
  end
  
  def new
    @rooms = Room.all
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      flash[:notice] = "Room successfully created"
      redirect_to @room
    else
      flash[:alert] = "Something went wrong"
      render 'new'
    end
  end

  def edit
    @rooms = Room.all
    @room = Room.find(params[:id])
  end

  def show
    @rooms = Room.all
    @room = Room.find(params[:id])
  end

  def update
    @room = Room.find(params[:id])
      if @room.update(room_params)
        flash[:notice] = "Room was successfully updated"
        redirect_to @room
      else
        flash[:alert] = "Something went wrong"
        render 'edit'
      end
  end

  def destroy
    @room = Room.find(params[:id])
    @room.destroy
    flash[:danger] = " Room destroyed successfully"
    redirect_to rooms_path
  end
  

  private
  def room_params
    params.require(:room).permit(:title, :description, images: [])
  end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carousel_helper.rb
module CarouselHelper
  def carousel_for(images)
    Carousel.new(self, images).html
  end

  class Carousel
    def initialize(view, images)
      @view, @images = view, images
      @uid = "carouselExampleIndicators"
    end

    def html
      content = safe_join([indicators, slides, controls])
      content_tag(:div, content, id: uid, class: 'carousel slide')
    end

    private

    attr_accessor :view, :images, :uid
    delegate :link_to, :content_tag, :image_tag, :safe_join, to: :view

    def indicators
      items = images.count.times.map { |index| indicator_tag(index) }
      content_tag(:ol, safe_join(items), class: 'carousel-indicators')
    end

    def indicator_tag(index)
      options = {
        class: (index.zero? ? 'active' : ''),
        data: { 
          target: uid, 
          slide_to: index
        }
      }

      content_tag(:li, '', options)
    end

    def slides
      items = images.map.with_index { |image, index| slide_tag(image, index.zero?) }
      content_tag(:div, safe_join(items), class: 'carousel-inner')
    end

    def slide_tag(image, is_active)
      options = {
        class: (is_active ? 'carousel-item active' : 'carousel-item'),
      }

      content_tag(:div, image_tag(image, :size => "600x400"), options)
    end

    def controls
      safe_join([control_tag('prev'), control_tag('next')])
    end

    def control_tag(direction)
      options = {
        class: "carousel-control-#{direction} ",
        data: { slide: direction == 'prev' ? 'prev' : 'next' }
      }

      icon = content_tag(:i, '', class: "carousel-control-#{direction}-icon bg-info text-primary")
      control = link_to(icon, "##{uid}", options)
    end
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper


end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul class="d-flex justify-content-center">
      <li><%= link_to '<i class="fa fa-facebook-square fa-2x"></i>'.html_safe, "https://www.facebook.com/omeshwor.shrestha/", :target => "_blank" %></li>
      <li><%= link_to "<i class='fa fa-comment fa-2x'></i>".html_safe, "http://m.me/omeshwor.shrestha", :target => "_blank" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_messages.html.erb
<div class="col">
    <% if notice %>
    	<div class='alert alert-success'>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
    		<%= notice %>
    	</div>
    <% end %>

    <% if alert %>
    	<div class='alert alert-danger'>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
    		<%= alert %>
    	</div>
    <% end %>

</div>

app/views/layouts/_side_bar.html.erb
<div class="col-2 left-col">
  <% if @rooms.exists? %>
    <% @rooms.each do |room| %>
      <a href="<%= room_path(room) %>"><%= room.title %></a>
    <% end %>
  <% else %>
    <p>No Rooms to display</p>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HotelApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/34ca5c7aa9.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <nav class="navbar">
      <%= link_to root_path, class:"navbar-brand" do %>
        <%= image_tag "brand.jpg", class:"navbar-brand" %>
      <% end %>
    </nav>
    <div class="row">
      <%= render 'layouts/side_bar' %>
      <div class="col-7 center-col">
        <%= render "layouts/messages" %>
        <%= yield %>
      </div>
      <div class="col-3 right-col">
        <p>Menu</p>
        <ol>
          <li>item 1</li>
          <li>item 2</li>
          <li>item 3</li>
        </ol>
      </div>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/rooms/_room_form.html.erb
<%= form_for @room do |f| %>
  <div class="form group row">
    <div class="col-form-label col-3">
      <%= f.label :"Room Name" %>
    </div>
    <div class="col-4">
      <%= f.text_field :title, class: "form-control", placeholder: "Room name", autofocus: true %>
    </div>
  </div>
  <div class="form group row">
    <div class="col-form-label col-3">
      <%= f.label :description %>
    </div>
    <div class="col-4">
      <%= f.text_area :description, class: "form-control" %>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-form-label col-3">
      <%= f.label :pictures %>
    </div>
    <div class="col-4">
      <%= f.file_field :images, multiple: true %>
    </div>
  </div>
  <div class="form-group row">
    <div class="offset-4">
      <%= f.submit class: "btn btn-primary"%>
    </div>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1 align="center">Update Room</h1>
<%= render 'room_form' %>

app/views/rooms/index.html.erb
<h1>WELCOME TO HOTEL</h1>

<%= link_to "New Room", new_room_path, class: "btn btn-primary" %>
<div class="accordion" id="accordionExample">
  <% @rooms.each do |room| %>
  <div class="card">
    <div class="card-header" id="<%= room.id %><%= room.title %>">
      <h2 class="mb-0">
        <button class="btn btn-link btn-block text-left" type="button" data-toggle="collapse" data-target="#collapse<%= room.id %>" aria-expanded="false" aria-controls="collapse<% room.id %>">
          <%= room.title %>
        </button>
      </h2>
    </div>

    <div id="collapse<%= room.id %>" class="collapse" aria-labelledby="<%= room.id %><%= room.title %>" data-parent="#accordionExample">
      <div class="card-body">
        <h5 class="card-title"><%= room.description %></h5>
        <%= link_to  "Show Room", room_path(room), class: "btn btn-primary" %>
      </div>
      
    </div>
  </div>
  <% end %>
</div>

app/views/rooms/new.html.erb
<h1 align="center">Add New Room</h1>
<%= render 'room_form' %>

app/views/rooms/show.html.erb
<div class="card" style="width: 100%">
  <%= carousel_for(@room.images) %>
  <div class="card-body">
    <h5 class="card-title"><%= @room.title %></h5>
    <p class="card-text"><%= @room.description %></p>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Features: </li>
    <li class="list-group-item">Price: </li>
    <li class="list-group-item">No of People: </li>
  </ul>
  <div class="card-body">
    <%= link_to "Edit Room", edit_room_path(@room), class:"btn btn-info" %>
    <%= link_to "Delete Room", room_path(@room), class:"btn btn-danger", method: :delete, data: { confirm: "Are you sure?"} %>
  </div>
</div>